// GET ALL COUNTRIES
export const GET_COUNTRIES_PENDING = "GET_COUNTRIES_PENDING";
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS";
export const GET_COUNTRIES_FAIL = "GET_COUNTRIES_FAIL";

// GET COUNTRY DETAILS
export const GET_COUNTRY_DETAIL_PENDING = "GET_COUNTRY_DETAIL_PENDING";
export const GET_COUNTRY_DETAIL_SUCCESS = "GET_COUNTRY_DETAIL_SUCCESS";
export const GET_COUNTRY_DETAIL_FAIL = "GET_COUNTRY_DETAIL_FAIL";
